/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Linux_Docs",
  "tagline": "linux documentation by ariaf",
  "favicon": "img/favicon.png",
  "url": "https://ariaf.my.id",
  "baseUrl": "/linux_docs/",
  "organizationName": "ariafatah0711",
  "projectName": "linux_docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "id",
    "locales": [
      "id"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/runner/work/docs_aria/docs_aria/sidebars.js",
          "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/docs/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/blog/"
        },
        "theme": {
          "customCss": "/home/runner/work/docs_aria/docs_aria/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "storage",
        "path": "storage",
        "routeBasePath": "storage",
        "sidebarPath": "/home/runner/work/docs_aria/docs_aria/sidebars.js",
        "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/storage/"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "cybersec",
        "path": "cybersec",
        "routeBasePath": "cybersec",
        "sidebarPath": "/home/runner/work/docs_aria/docs_aria/sidebars.js",
        "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/cybersec/"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "scripting",
        "path": "scripting",
        "routeBasePath": "scripting",
        "sidebarPath": "/home/runner/work/docs_aria/docs_aria/sidebars.js",
        "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/scripting/"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "android_debug",
        "path": "android_debug",
        "routeBasePath": "android_debug",
        "sidebarPath": "/home/runner/work/docs_aria/docs_aria/sidebars.js",
        "editUrl": "https://github.com/ariafatah0711/linux_docs/tree/main/android_debug/"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Linux Docs",
      "logo": {
        "alt": "Linux Docs",
        "src": "img/profil.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "default",
          "position": "left",
          "label": "linux",
          "docsPluginId": "default"
        },
        {
          "type": "docSidebar",
          "sidebarId": "default",
          "position": "left",
          "label": "storage",
          "docsPluginId": "storage"
        },
        {
          "type": "docSidebar",
          "sidebarId": "default",
          "position": "left",
          "label": "cybersec",
          "docsPluginId": "cybersec"
        },
        {
          "type": "docSidebar",
          "sidebarId": "default",
          "position": "left",
          "label": "scripting",
          "docsPluginId": "scripting"
        },
        {
          "type": "docSidebar",
          "sidebarId": "default",
          "position": "left",
          "label": "android_debug",
          "docsPluginId": "android_debug"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/ariafatah0711/linux_docs",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "linux_docs",
              "to": "/linux_docs"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://s.id/dev-universe"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/ariafatah0711/linux_docs"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 My Project, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
