name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Izin untuk menulis ke branch gh-pages
  pages: write
  id-token: write

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Website
        run: npm run build
      
      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git --work-tree=build add --all
          git --work-tree=build commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4